### ISSUE TITLE
v is undefined

### ISSUE THREAD

**Issue by ZIOOIZ8** [shizunge/endlessh-go#115]
![grafik](https://github.com/user-attachments/assets/b6b193aa-9dec-4ed8-ab86-fd59304721ca)

I had the error as shown in the screenshot above and tried to completely rebuild and deploy all my docker containers and the Grafana dashboard. I also deleted all storage volumes and completely rebuilt the stack, but unfortunately the error did not disappear. Here is my docker stack which I run in my portainer:

```
version: '3.8'
services:
  endlessh:
    image: shizunge/endlessh-go:latest
    container_name: endlessh
    command:
      - -interval_ms=1000
      - -logtostderr
      - -v=1
      - -enable_prometheus
      - -geoip_supplier=ip-api
    ports:
      # SSH port
      - 2222:2222
      # Prometheus metrics port
      - 2112:2112
    restart: always
    stdin_open: true # docker run -i
    tty: true # docker run -t

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command: 
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=45d
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --web.enable-admin-api
    ports:
      - 9090:9090
    volumes:
      - /var/lib/docker/volumes/endlessh_prometheus/_data/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    restart: always
    stdin_open: true # docker run -i
    tty: true # docker run -t
volumes:
  prometheus:
```

Am I doing something wrong, or is there a bug somewhere in the containers?
