### ISSUE TITLE
Prometheus Data Source

### ISSUE THREAD

**Issue by Cheezzhead** [shizunge/endlessh-go#142]
Hey, I'm having trouble adding the prometheus `/metrics` endpoint as a Prometheus data source in Grafana. 

I have tried `http://endlessh:2112/metrics`, `http://endlessh:2112/`, and `http://endlessh:2112` but all of them result in the error `404 Not Found - There was an error returned querying the Prometheus API.` in Grafana. The endpoint is definitely reachable as running `curl endlessh:2112/metrics` in the Grafana container returns the data correctly.

Compose file:
```yaml
endlessh:
    image: shizunge/endlessh-go:latest
    container_name: endlessh
    # ...
    command: |-
      -logtostderr
      -v=1
      -geoip_supplier=max-mind-db
      -max_mind_db=/storage/data/geoip2db/GeoLite2-City.mmdb
      -enable_prometheus
```

What am I doing wrong?

**Comment by samhaswon** [comment]
I'm pretty sure that the `endlessh-go` container only has a Prometheus client by default. The easy way to fix this is to include a Prometheus container in the stack. What I have running is basically the example from this repo here: https://github.com/shizunge/endlessh-go/tree/main/examples/docker-simple 

Just in case you have issues with that example, here's what works for me:
```yml
services:
  endlessh-go:
    image: shizunge/endlessh-go
    container_name: endlessh-go
    ports:
      - "2222:2222"
      - "2112:2112"
    restart: unless-stopped
    command:
      - "-logtostderr"
      - "-v=1"
      - "-geoip_supplier=ip-api"
      - "-enable_prometheus"
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=45d
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --web.enable-admin-api
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus

volumes:
  grafana-storage: {}
  prometheus:
```
Note: I am running this as a part of a larger stack with another type of tarpit. 

Now, in Grafana, you can add Prometheus as `http://prometheus:9090` for the server URL. Docker networking allows you to reference the Prometheus container by its hostname, making this fairly easy.
