### ISSUE TITLE
Countries not displaying

### ISSUE THREAD

**Issue by Drone8334** [shizunge/endlessh-go#154]
After some trial and error and reading through other helpful/resolved issues, I got up and running last night. Running docker compose on Ubuntu 24.04.1 LTS, which is itself a Proxmox VM. No issues with passing port 22 through opnsense to 2222 on endlessh-go. However, my countries are showing as 'unknown' and the IPs are not resolving to the country:

![Image](https://github.com/user-attachments/assets/8d64c863-8220-4767-900e-a38ea2bb9d25)

I initially had it set to ip-api, as in the docker-simple docker-compose.yml. Thinking that this was the issue, I changed it to GeoLite2-Country. I downloaded the Geolite2-Country.mmdb file from maxmind and it's in the same directory as the docker-compose.yml. My compose file is as below:

```
services:

  endlessh:
    container_name: endlessh
    image: shizunge/endlessh-go:latest
    restart: always
    command:
      - -interval_ms=1000
      - -logtostderr
      - -v=1
      - -enable_prometheus
      - -geoip_supplier=max-mind-db
      - -max_mind_db=GeoLite2-Country.mmdb
    networks:
      - example_network
    ports:
      - 2222:2222 # SSH port
      - 192.168.1.250:2112:2112 # Prometheus metrics port

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=45d
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --web.enable-admin-api
    networks:
      - example_network
    ports:
      - 192.168.1.250:9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana2
    restart: always
    networks:
      - example_network
    ports:
      - 192.168.1.250:3050:3000
    environment:
      - GF_SECURITY_ADMIN_USER=*****
      - GF_SECURITY_ADMIN_PASSWORD=*****
    volumes:
      - grafana_var:/var/lib/grafana/
      - ./grafana-datasource.yml:/etc/grafana/provisioning/datasources/prometheus.yml

networks:
  example_network:


volumes:
  prometheus:
  grafana_var:
```

I'm sure I'm missing something obvious, can I get some help with this? Thank you.
