### ISSUE TITLE
Max-Mind-DB how to?

### ISSUE THREAD

**Issue by RPiList** [shizunge/endlessh-go#39]
Hi,

any chance of getting an example on how to use max-mind-db on endlessh-go?

Because there are three different db on max-mind an each comes in two flavors.

The linked online alternatives IP-API.com and freegeoip.live are offline.

> -geoip_supplier=max-mind-db -max_mind_db=/absolute/path/to/GeoLite2-Country.mmdb
> -geoip_supplier=max-mind-db -max_mind_db=./GeoLite2-Country.mmdb
> -geoip_supplier=max-mind-db -max_mind_db ./GeoLite2-Country.mmdb

I guess I am using the wrong database because none of them worked... 

could you point me in the right direction? Thankx.

**Comment by EuleMitKeule** [comment]
Moin!

For me the `GeoLite2-Country.mmdb` is working fine.
This is my docker-compose config:

```yaml
services:
  endlessh:
    image: ghcr.io/shizunge/endlessh-go:20221012
    container_name: endlessh
    restart: unless-stopped
    command:
      - -interval_ms=1000
      - -logtostderr
      - -v=1
      - -enable_prometheus
      - -geoip_supplier=max-mind-db
      - -max_mind_db=/geoip/GeoLite2-Country.mmdb
    ports:
      - 2222:2222
      - 2112:2112
    volumes:
      - /volume1/docker/geoip/GeoLite2-Country.mmdb:/geoip/GeoLite2-Country.mmdb
```

As you can see I mounted the `GeoLite2-Country.mmdb` file from the docker host into the endlessh container to the path `/geoip/GeoLite2-Country.mmdb`. Maybe you specified a host path for the `-max_mind_db` argument instead of a container path?

Also maybe the database file itself is at fault. I use the official maxmind geoipupdate docker container to keep my database files updated. This is an example config for that container:
```yaml
services:
  geoip:
    image: maxmindinc/geoipupdate:v4.10
    container_name: geoip
    restart: unless-stopped
    environment:
      - GEOIPUPDATE_ACCOUNT_ID=$GEOIPUPDATE_ACCOUNT_ID
      - GEOIPUPDATE_LICENSE_KEY=$GEOIPUPDATE_LICENSE_KEY
      - GEOIPUPDATE_EDITION_IDS=GeoLite2-ASN GeoLite2-City GeoLite2-Country
      - GEOIPUPDATE_FREQUENCY=168
    volumes:
      - /volume1/docker/geoip:/usr/share/GeoIP
```
![image](https://user-images.githubusercontent.com/47421406/208410376-f1709cb7-0978-41a9-b009-0bb7a7de5238.png)
