### ISSUE TITLE
[QUESTION] Where does the 'Normal' log output go to? (fail2ban)

### ISSUE THREAD

**Issue by BlackWolfWoof** [shizunge/endlessh-go#42]
I am trying to get the logs so fail2ban can read them, but wondered where the logs to to so i can bind them to a volume/mount.
```yml
version: '3.5'
services:
  endlessh:
    container_name: tarpit-endlessh
    image: shizunge/endlessh-go:latest
    restart: unless-stopped
    command:
      - -interval_ms=1000
      - -logtostderr
      - -v=1
      - -enable_prometheus
      - -geoip_supplier=ip-api
      - -log_dir=/example
    ports:
      - 22:2222
#      - 9101:2112 #prometheus port (now handled via networks)
    networks:
    - default
    - prometheus
    volumes:
    - /home/user/example:/example

networks:
  prometheus:
    external: true
```
Here i tried to put it into /example of the container and then ls /home/user/example, but nothing was logged there.
I am probably doing something wrong so if you see what mistake i made could you please point it out to me, thanks :)
